# fly.toml app configuration file generated for music-arena-demo on 2025-04-23T12:25:29-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

# gclef-at-cmu fly.io
app = 'music-arena-dev'
primary_region = 'atl'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
