# Frontend dev deployment
systems:
  "noise:quiet":
    port: 20000
    args:
      max_batch_size: 1
      max_delay: 4.0
  "noise:loud":
    port: 20001
    args:
      max_batch_size: 1
      max_delay: 4.0

weights:
  "noise:quiet/noise:loud": 1.0

components:
  frontend:
    enabled: true
    port: 21000
    vars:
      GATEWAY_URL: "http://host.docker.internal:21001"
      MINIMUM_LISTEN_TIME: 0.01
      GRADIO_ALLOWED_PATHS: "/music-arena/io/gateway"
  gateway:
    enabled: true
    port: 21001
    args:
      systems_base_url: "http://host.docker.internal"
      flakiness: 0.0
  systems:
    enabled: true